### ISSUE TITLE
Create version for the 23.08 freedesktop SDK

### ISSUE THREAD

**Issue by job79** [flathub/org.freedesktop.Sdk.Extension.php82#21]
Hello! I have been using this package together with the intellij flatpak. 
Some time ago intellij moved to the 23.08 SDK, making it impossible to use the php SDK.
To fix this I recompiled the php SDK for the newer freedesktop version, which is working great but I no longer receive updates. 

Could this repo be updated so it supports the newer version?

**Comment by ricvelozo** [comment]
I tried to use it with the VS Code and had the same problem.

**Comment by Lctrs** [comment]
[A PHP 8.3 extension for the 23.08 SDK is coming](https://github.com/flathub/flathub/pull/4845). For now, I don't plan to make a 23.08 build for PHP 8.2.

**Comment by Lctrs** [comment]
[PHP 8.3 is now available for the 23.08 SDK](https://github.com/flathub/org.freedesktop.Sdk.Extension.php83).
