### ISSUE TITLE
Freedesktop SDK 24.08 will be dropping appstream-compose

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.freedesktop.Sdk.Extension.php82#30]
Please remove manual compose or switch to appstreamcli 

See https://docs.flatpak.org/en/latest/extension.html#extension-manifest for the commands

**Comment by Lctrs** [comment]
We won't be making a 24.08 version of this extension, but we'll keep that in mind for the PHP 8.3 extension or the next PHP version extension.
